### ISSUE TITLE
How to run TransMatcher?

### ISSUE THREAD

**Issue by justopit** [ShengcaiLiao/TransMatcher#3]

**Comment by ShengcaiLiao** [comment]
Now it is described in the [README](https://github.com/ShengcaiLiao/TransMatcher) of this project. 

It is based on the [QAConv](https://github.com/ShengcaiLiao/QAConv) 2.0 code, and the requirements and usage are quite similar. For a quick run, please try the [demo.sh](https://github.com/ShengcaiLiao/TransMatcher/blob/main/demo.sh).
